config/routes.rb
Rails.application.routes.draw do
  resources :articles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  get 'welcome/about'

  get 'signup', to: 'users#new'

  resources :users, except: [:new]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { minimum: 3, maximum: 50}
  validates :description, presence: true, length: { minimum: 10, maximum: 500}
  validates :user_id, presence: true
  end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  before_save { self.email=email.downcase }
  validates :username, presence: true,
            uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
   VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
             uniqueness: { case_sensitive: false }, length: { maximum: 100 },
             format: { with: VALID_EMAIL_REGEX }

  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)
    @article.user = User.first

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice:  "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new

    @user = User.new

  end


  def create

    @user = User.new(user_params)

    if @user.save

      flash[:success] = "Welcome to the Test App #{@user.username}"

      redirect_to articles_path

    else

      render 'new'

    end
  end

  def show
    @user=User.find(params[:id])
  end

    def edit

      @user = User.find(params[:id])

    end

    def update

      @user = User.find(params[:id])

      if @user.update(user_params)

        flash[:success] = "Your account was updated successfully"

        redirect_to articles_path

      else

        render 'edit'

      end
      end











  private

  def user_params

    params.require(:user).permit(:username, :email, :password)

  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home

  end
  def about

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80})

    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)

    size = options[:size]

    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"

    image_tag(gravatar_url, alt: user.username, class: "img-circle")

  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_article.html.erb
<% object_id.each do |article| %>

  <div class="row">

    <div class="col-xs-8 col-xs-offset-2">

      <div class="well well-lg">

        <div class="article-title">

          <%= link_to article.title, article_path(article) %>

        </div>

        <div class="article-body">

          <%= truncate(article.description, length: 100) %>

          <div class="article-meta-details">

            <small>Created by: <%= article.user.username if article.user%>,

              <%= time_ago_in_words(article.created_at) %> ago,

              last updated: <%= time_ago_in_words(article.updated_at) %> ago</small>

          </div>



        </div>

        <div class="article-actions">

          <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-primary" %>

          <%= link_to "Delete this article", article_path(article), method: :delete,

                      data: { confirm: "Are you sure you want to delete the article?"},

                      class: "btn btn-xs btn-danger" %>

        </div>

      </div>

    </div>

  </div>

<% end %>

app/views/articles/_form.html.erb
<div class="row" >
  <div class ="col-md-12">

    <%= form_for @article, html:  {class:'form-horizontal',role: 'form'} do |f|%>

      <% if @article.errors.any? %>

        <div class="row">

          <div class="col-xs-8 col-xs-offset-2">

            <div class="panel panel-danger">

              <div class="panel-heading">

                <h2 class="panel-title">

                  <%= pluralize(@article.errors.count, "error") %>

                  prohibited this article from being saved:

                </h2>

                <div class="panel-body">

                  <ul>

                    <% @article.errors.full_messages.each do |msg| %>

                      <li><%= msg %></li>

                    <% end %>

                  </ul>

                </div>

              </div>

            </div>

          </div>

        </div>

      <% end %>






      <div class="form-group">
        <div class="control-label col-sm-2">

          <%= f.label :title %>
        </div>
        <div class="col-sm-8">

          <%= f.text_field :title, class: "form-control" , placeholder: "Title of article", autofocus: true%>
        </div>
      </div>
      <div class="form-group">

        <div class="control-label col-sm-2">
        <%= f.label :description %>
        </div>

        <div class="col-sm-8">

          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
        </div>
      </div>


      <div class="form-group">

        <div class="col-sm-offset-2 col-sm-10">

          <%= f.submit class: 'btn btn-primary btn-lg' %>

        </div>

      </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">

      [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]

    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 align="center" > Editing Article</h1>

<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1 align="center">Listing All Articles</h1>

<%= render 'article',  object_id: @articles %>

app/views/articles/new.html.erb
<h1 align="center">Create New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>


<h2 align="center">Title: <%= @article.title %></h2>

<div class="well col-xs-8 col-xs-offset-2">

  <h4 class=" description"><strong>Description:</strong></h4>

  <hr>

  <%= simple_format(@article.description) %>

  <div class="article-actions">

    <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>

    <%= link_to "Delete this article", article_path(@article), method: :delete,

                data: { confirm: "Are you sure you want to delete the article?"},

                class: "btn btn-xs btn-danger" %>

    <%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success" %>

  </div>

</div>

app/views/layouts/_footer.html.erb
<div class="container">
<footer class="footer" >
  <small>
    Copyright &copy; <a href="https://github.com/muhammad-anas-2/Last-App" >Last App Code At GitHub </a>
     by <a href="bitfi16a537@pucit.edu.pk" >Muhammad Anas</a>
  </small>
  <nav>
    <ul>
      <li><%=link_to "About", welcome_about_path %></li>
    </ul>
  </nav>
</footer>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <ul>
    <li><%= msg %></li>
  </ul>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a
      <%= link_to "Test App", root_path, class: "navbar-brand" , id: "logo"  %>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <a
          <%=link_to"Home", root_path, class:"nav-item"%>

          </a>
        </li>

        <li class="dropdown">
          <button class="dropbtn">Articles</button>
          <div class="dropdown-content">
            <a
             <%= link_to " Create", new_article_path %>
            </a>
            <a
            <%= link_to "List", articles_path %>
            </a>
            <a
            <%= link_to "About", welcome_about_path %>
            </a>
          </div>


        </li>

      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LastApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css' %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>
  <body>


  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>

  <div class= "container">
  <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/users/_form.html.erb
<div class='row'>

  <div class='col-xs-12'>

    <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>



      <% if @user.errors.any? %>

        <div class="row">

          <div class="col-xs-8 col-xs-offset-2">

            <div class="panel panel-danger">

              <div class="panel-heading">

                <h2 class="panel-title">

                  <%= pluralize(@user.errors.count, "error") %>

                  prohibited this article from being saved:

                </h2>

                <div class="panel-body">

                  <ul>

                    <% @user.errors.full_messages.each do |msg| %>

                      <li><%= msg %></li>

                    <% end %>

                  </ul>

                </div>

              </div>

            </div>

          </div>

        </div>

      <% end %>




      <div class="form-group">

        <div class="control-label col-sm-2">

          <%= f.label :username %>

        </div>

        <div class="col-sm-8">

          <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>

        </div>

      </div>

      <div class="form-group">

        <div class="control-label col-sm-2">

          <%= f.label :email %>

        </div>

        <div class="col-sm-8">

          <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>

        </div>

      </div>

      <div class="form-group">

        <div class="control-label col-sm-2">

          <%= f.label :password %>

        </div>

        <div class="col-sm-8">

          <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>

        </div>

      </div>

      <div class="form-group">

        <div class="col-sm-offset-2 col-sm-10">

          <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: 'btn btn-primary btn-lg') %>

        </div>

      </div>

    <% end %>

    <div class="col-xs-4 col-xs-offset-4">

      [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]

    </div>

  </div>

</div>

app/views/users/edit.html.erb
<h1 align="center">Edit Your Account</h1>
<%=render'form'%>

app/views/users/new.html.erb
<h1 align="center">Signup For Test App</h1>
<%=render'form'%>

app/views/users/show.html.erb
<h1 align = "center">Welcome to <%= @user.username %>'s page</h1>
<div class="row">

  <div class="col-md-4 col-md-offset-4 center">

    <%= gravatar_for @user, size: 150 %>

  </div>

</div>

<h4 align="center"><%= @user.username %>'s articles</h4>
<%=render 'articles/article', object_id: @user.articles %>

app/views/welcome/about.html.erb
<h1> This Is My About Page </h1>
<%= link_to ' Home ', root_path %>

app/views/welcome/home.html.erb
<div class=" center jumbotron" >
<h1>Test App </h1>
  <h2>
<%=link_to "Sign Up" , new_article_path, class: "btn btn-danger btn-lg"%>
  </h2>
</div>